---
- name: My Test Playbook
  hosts: all
  become: true
  tasks:
    - name: installing packages
      yum:
        name: ['git', 'wget', 'tree', 'mysql', 'make', 'gcc', 'telnet', 'which', 'docker*']
        state: installed

