---
- name: setup tomcat
  hosts: all
  become: true
  tasks:
    - name: installing java package
      yum:
        name: java 
        state: installed
      when: ansible_os_family == "RedHat"

    - name: installing java package on ubuntu
      apt:
        name: default-jdk
        state: present
      when: ansible_os_family == "Debian"

    - name: downloading tomcat
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.84/bin/apache-tomcat-8.5.84.tar.gz
        dest: /opt

    - name: extracting package
      unarchive:
        src: /opt/apache-tomcat-8.5.84.tar.gz
        dest: /opt
        remote_src: true

    - name: adding execute permissions
      file:
        path: /opt/apache-tomcat-8.5.84/bin/startup.sh
        mode: 0777

    - name: start tomcat service
      shell: ./startup.sh
      args:
        chdir: /opt/apache-tomcat-8.5.84/bin
